### ISSUE TITLE
Error when navigating

### ISSUE THREAD

**Issue by pltarg** [kalismeras61/flutter_page_transition#11]
Hi, i keep getting this error, although i copied and pasted the example.

flutter: ══╡ EXCEPTION CAUGHT BY GESTURE 
flutter: The following NoSuchMethodError was thrown while handling a gesture:
flutter: The getter 'isInitialRoute' was called on null.
flutter: Receiver: null

Any ideas?

**Comment by kalismeras61** [comment]
Problem fixed. Please update your version with 1.1.4

**Comment by pltarg** [comment]
> Problem fixed. Please update your version with 1.1.4

Oh thanks! now works perfectly.

Thanks for taking the time to answer me.

Salutes!

**Comment by kalismeras61** [comment]
Your welcome.
