### ISSUE TITLE
Feature Request: Setting the route name

### ISSUE THREAD

**Issue by numen31337** [kalismeras61/flutter_page_transition#16]
Currently, there is no ability to set the page route name which is part of `RouteSettings` and is hidden behind the `PageTransition` class implementation. Without this, it is impossible to use some `Navigator's` features such as `popUntil`.

**Comment by kalismeras61** [comment]
I will add RouteSettings  in few days.

**Comment by YatsenkoDev** [comment]
Facing issue with arguments passing, so waiting for RouteSettings also.

**Comment by kalismeras61** [comment]
Now you can use RouteSettings! Please read Readme.md file and look at example folder for usage!

**Comment by kalismeras61** [comment]
Hey @numen31337 , if it is ok for you please close this.
