### ISSUE TITLE
Can you write implementation for `pageTransitionsTheme` ?

### ISSUE THREAD

**Issue by Hellomik2002** [kalismeras61/flutter_page_transition#22]

**Comment by leszekkrol** [comment]
Any update?

**Comment by gogulnathv** [comment]
@Hellomik2002 & @leszekkrol,
pageTransitionsTheme takes - TargetPlatform and PageTransitionsBuilder
In this plugin we use pageBuilder for transition.

can any one of you provide a scenario or how you want this to be implemented
