### ISSUE TITLE
Black Screen during 'downToUp' transitions in Flutter 1.17.1

### ISSUE THREAD

**Issue by elvisgn** [kalismeras61/flutter_page_transition#24]
Hi,
I'm having a problem after upgrading to flutter 1.17.1.

On previously working 'downToUp' transitions, I'm now seeing a black box in the upper part of the screen. Its almost like downToUp is partically rightToLeft before moving upwards. By the way I'm using a Stack with a Scaffold.

Sorry, not able to paste code.

**Comment by abbas-25** [comment]
Same. Happens with me most of the time when using a combination of different transitions. Say A to B is right to left and B to C is down to up. In these cases, there is a black screen in between B to C and it looks ugly. I don't know possibly I must be doing something wrong. Using the original MaterialPageRoute avoids this problem.

**Comment by bratlove123** [comment]
Still happen on version +5. The first navigation is OK, but the next navigation from the first one will have the black animation. Please fix that. Really appreciate. Thanks.
