### ISSUE TITLE
The transition process is incorrect

### ISSUE THREAD

**Issue by hahai96** [kalismeras61/flutter_page_transition#25]
![Screen Recording 2020-05-27 at 5 40 01 PM](https://user-images.githubusercontent.com/23280338/83010181-12af8580-a042-11ea-962c-53b6985a7a84.gif)

> 
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.3 19D76, locale en-US)
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     ✗ Android license status unknown.
>       Try re-installing or updating your Android SDK Manager.
>       See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3)
> [✓] Android Studio (version 3.6)
> [✓] Connected device (1 available)
> 
> ! Doctor found issues in 1 category.
> ha-hais-MacBook-Pro:musicword_flutter ha_hai$

**Comment by kalismeras61** [comment]
Can you explain more?

**Comment by rodineijf** [comment]
You can simulate this by pushing a downToUp page inside a rightToLeft pushed page. In this case, the right-to-left exit animation should not happen.

This only occurs in flutter 1.17

This bug appears to have been caused because of this PR.
https://github.com/flutter/flutter/pull/45750

**Comment by hahai96** [comment]
@kalismeras61 See the old routes when new routes are created, they move up to create a black screen.

**Comment by kalismeras61** [comment]
It should be fixed.
