### ISSUE TITLE
Parallax effect when sliding like MaterialPageRoute on iOS

### ISSUE THREAD

**Issue by proformance** [kalismeras61/flutter_page_transition#28]
Would it be possibel to do something in style with Parallax effect when sliding like MaterialPageRoute on iOS ?

Best regards

**Comment by JackBeattie** [comment]
if you are interested, would you like me to submit a package to do that? I built a method a while ago to emulate the ios parallax with the correct swipe gestures. the one bundled with CupertinoPageScaffold doesn't feel the same and still doesn't work properly with hero widgets. My implementation needs a bit of cleaning but it has custom handlers to support gesture interrupts and hero widgets animating between pages.

**Comment by girish54321** [comment]
Hi For Parallax effect i am doing this
```
if (Platform.isIOS) {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => child,
        ),
      );
    } else {
      Navigator.push(
          context,
          PageTransition(
            type: PageTransitionType.rightToLeft,
            child: child,
          ));
    }
```
