### ISSUE TITLE
Pop duration

### ISSUE THREAD

**Issue by jamesnicholls04** [kalismeras61/flutter_page_transition#30]
Hi - thanks for the package!

I am wondering whether it would be possible to enforce that the 'pop' duration is equal to the duration of the 'push'?

Thanks!

**Comment by BastianHandly** [comment]
Asking myself the same question. It used to work but since a few flutter updates, it doesn't work anymore.

**Comment by jamesnicholls04** [comment]
> Asking myself the same question. It used to work but since a few flutter updates, it doesn't work anymore.

I ended up making my own routes:

`class FadeRoute extends PageRouteBuilder {
  final Widget page;
  FadeRoute({@required this.page})
      : super(
          pageBuilder: (
            BuildContext context,
            Animation<double> animation,
            Animation<double> secondaryAnimation,
          ) =>
              page,
          transitionDuration: Duration(milliseconds: 0),
          reverseTransitionDuration: Duration(milliseconds: 0),
          transitionsBuilder: (
            BuildContext context,
            Animation<double> animation,
            Animation<double> secondaryAnimation,
            Widget child,
          ) =>
              FadeTransition(
            opacity: animation,
            child: child,
          ),
        );
}`

As you can see, you can define the durations separately. Hope this helps!

**Comment by princestha** [comment]
Would love to have this feature, or if someone can guide me, would love to open a PR. Thank you

**Comment by joaovperin** [comment]
> 
> 
> > Asking myself the same question. It used to work but since a few flutter updates, it doesn't work anymore.
> 
> I ended up making my own routes:
> 
> `class FadeRoute extends PageRouteBuilder { final Widget page; FadeRoute({@required this.page}) : super( pageBuilder: ( BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, ) => page, transitionDuration: Duration(milliseconds: 0), reverseTransitionDuration: Duration(milliseconds: 0), transitionsBuilder: ( BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child, ) => FadeTransition( opacity: animation, child: child, ), ); }`
> 
> As you can see, you can define the durations separately. Hope this helps!

Hey, can you help me using that?
I don't know how to make this work in a modal.

I'm currently doing this:
```dart
  void _openModalAndDoSomething(BuildContext ctx) {
    showModalBottomSheet(
      context: ctx,
      builder: (_) {
        return MyForm(onSubmit: (dynamic myData) async {
             await doSomething(myData);
             Navigator.of(ctx).pop();
        });
      },
    );
  }```

**Comment by JackBeattie** [comment]
It is more simple than that. Just add-in the missing functionality to the library and copy the file to a local directory within the lib folder. It's only a single file so it isn't too complicated. within the `pageBuilder` method, below the line `transitionDuration: duration,` insert the line `reverseTransitionDuration: reverseDuration,` and declare it as a final for the class by adding `final Duration reverseDuration;`. The last thing to do is insert `this.reverseDuration = const Duration(milliseconds: 300),` in the constructor argument declaration and then you can use the `reverseDuration` property as you would `duration` when using it. I think this broke when the material package was updated and stopped inferring the reverse duration from the duration if unset.

**Comment by kalismeras61** [comment]
@jamesnicholls04  I added reverse transition please use version: 1.1.7+3.

**Comment by rohan-kadkol** [comment]
Here's one way of specifying the forward and reverse durations:

```dart
Navigator.of(context).push(
  PageRouteBuilder(
    transitionDuration: Duration(milliseconds: 800), // Forward Duration
    reverseTransitionDuration: Duration(milliseconds: 800), // Reverse Duration
    pageBuilder: (BuildContext context,
        Animation<double> animation,
        Animation<double> secondaryAnimation) {
      return NewScreen();
    },
    transitionsBuilder: (BuildContext context,
        Animation<double> animation,
        Animation<double> secondaryAnimation,
        Widget child) {
      return FadeTransition(
        opacity: animation,
        child: child,
      );
    },
  ),
);
```
