### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by obrand69** [kalismeras61/flutter_page_transition#32]
During build, I get the following error:
[ +904 ms] ../../flutter/.pub-cache/hosted/pub.dartlang.org/page_transition-1.1.7+3/lib/src/page_transition.dart:62:11: Error: No named parameter with the name
'reverseTransitionDuration'.
[        ]           reverseTransitionDuration: reverseDuration,

I am NOT on the latest Flutter version. You should protect this version and only make it available for later Flutter versions

**Comment by kalismeras61** [comment]
@obrand69 did you run flutter clean ? The package update yesterday and I added pop duration.

**Comment by kalismeras61** [comment]
@obrand69 any update ?

**Comment by obrand69** [comment]
I had to hardcode the version with an override in my yaml file.
