### ISSUE TITLE
flutter app not running when this library imported ver 1.1.7+2 get pub worked but 7+3 downloading

### ISSUE THREAD

**Issue by marzookavc** [kalismeras61/flutter_page_transition#35]
Compiler message:
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/page_transition-1.1.7+3/lib/src/page_transition.dart:62:11: Error: No named parameter with the name
    'reverseTransitionDuration'.
              reverseTransitionDuration: reverseDuration,

....................................................................................

**Comment by kalismeras61** [comment]
reverseTransitionDuration added after flutter 1.22 stable. Are you using old version of flutter ?

**Comment by marzookavc** [comment]
No , now i am using older version (1.1.7+2)
its working perfectly fine

**Comment by kalismeras61** [comment]
> No , now i am using older version (1.1.7+2)
> its working perfectly fine

I mean flutter version. Can you run flutter doctor -v and put here results.

**Comment by marzookavc** [comment]
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.7 19H2, locale en-AE)
    • Flutter version 1.17.5 at /Users/ali/Desktop/flutter
    • Framework revision 8af6b2f038 (6 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ali/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

**Comment by kalismeras61** [comment]
@marzookavc as you see your Flutter version is too old. reverseDuration property is added after flutter 1.22 stable. If you upgrade your version you will not face this issue. Or you can keep it with page_transition 1.1.7+2
