### ISSUE TITLE
Wrong page transition effect when changing direction e.g. from topToBottom to bottomToTop.

### ISSUE THREAD

**Issue by robertflesch** [kalismeras61/flutter_page_transition#36]
If I do a number of topToBottom transitions, everything works great, but when I switch to bottomToTop, the page that is being left moves in the wrong direction. It moves as if I was doing another topToBottom. Unfortunately this is a critical feature for my team.  This effect is true for the leftToRight and the rightToLeft.

**Comment by valentinoguerra** [comment]
Same problem here

**Comment by robertflesch** [comment]
It looks like the secondaryAnimation is not being created the first time the transition is called. But I have no clue as to why. Any help from @kalismeras61 on this one?

When I add print statements in, I see this for the first time I call it. Logging animation, curve, and secondaryAnimation
(▶ 0.056; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation
(▶ 0.083; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation
(▶ 0.111; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation
...
(▶ 0.917; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation
(▶ 0.944; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation
(▶ 0.972; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation
(▶ 1.000; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation

the second time I run it (when it works ) the log looks like this
You can see the second screen transitioning on this one, the first time it appears to use a default animation?
Question is how to you get the animation to run on the departing screen the first time?

(⏭ 1.000; paused; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation
I/flutter (17162): topToBottom animation: kAlwaysCompleteAnimation➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation
(⏭ 1.000; paused; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: AnimationController#927f4(▶ 0.000; for PageTransition<dynamic>)➩ProxyAnimation➩ProxyAnimation
(▶ 0.056; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation
(⏭ 1.000; paused; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: AnimationController#927f4(▶ 0.056; for PageTransition<dynamic>)➩ProxyAnimation➩ProxyAnimation
(⏭ 1.000; paused; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: AnimationController#927f4(▶ 0.083; for PageTransition<dynamic>)➩ProxyAnimation➩ProxyAnimation
(▶ 0.083; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation
...
(▶ 0.889; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation
(⏭ 1.000; paused; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: AnimationController#927f4(▶ 0.917; for PageTransition<dynamic>)➩ProxyAnimation➩ProxyAnimation
(▶ 0.917; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation
(⏭ 1.000; paused; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: AnimationController#927f4(▶ 0.944; for PageTransition<dynamic>)➩ProxyAnimation➩ProxyAnimation
(▶ 0.944; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation
(⏭ 1.000; paused; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: AnimationController#927f4(▶ 0.972; for PageTransition<dynamic>)➩ProxyAnimation➩ProxyAnimation
(▶ 0.972; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation
(⏭ 1.000; paused; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: AnimationController#927f4(⏭ 1.000; paused; for PageTransition<dynamic>)➩ProxyAnimation➩ProxyAnimation
(⏭ 1.000; paused; for PageTransition<dynamic>)➩ProxyAnimation curve:_Linear secondaryanimaition: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation

**Comment by kalismeras61** [comment]
@robertflesch i add fix for that. Can you  test with version 1.1.7+6

**Comment by robertflesch** [comment]
Hi Yasin Ilhan
Thanks for responding and putting in a fix. My team was giving me a very
hard time with this bug.

So the fix eliminates the problem with the black screen. But it also kills
the nice two screens working as one transition.
The second screen just sits there and the new screen comes over it. Better
than the black screen, but not as nice as the two screens moving together
when it works.

thanks again for the fix
bob

**Comment by samry** [comment]
Hi there - still having this issue, anyone find a work around?

**Comment by kalismeras61** [comment]
Should be fixed latest version
