### ISSUE TITLE
Page transition where the "current page" and "new page" both slide across

### ISSUE THREAD

**Issue by benwinding** [kalismeras61/flutter_page_transition#37]
Is it possible to transition between pages, where both the "current page" and "new page" both slide across the screen like they are joined together?

Demo of what I mean:
![krossy_1](https://user-images.githubusercontent.com/11782590/103074207-0f509c80-4619-11eb-8982-2adfcd2f325d.gif)

**Comment by benwinding** [comment]
Okay I just found out how to achieve this, from [this medium article](https://medium.com/flutter-community/everything-you-need-to-know-about-flutter-page-route-transition-9ef5c1b32823). Giving this effect:

![1_5PIKSynhS-fImK8WikmBSQ](https://user-images.githubusercontent.com/11782590/103075029-ba158a80-461a-11eb-9125-cb5e78c8d7f8.gif)

``` dart
import 'package:flutter/material.dart';

class EnterExitRoute extends PageRouteBuilder {
  final Widget enterPage;
  final Widget exitPage;
  EnterExitRoute({this.exitPage, this.enterPage})
      : super(
          pageBuilder: (
            BuildContext context,
            Animation<double> animation,
            Animation<double> secondaryAnimation,
          ) =>
              enterPage,
          transitionsBuilder: (
            BuildContext context,
            Animation<double> animation,
            Animation<double> secondaryAnimation,
            Widget child,
          ) =>
              Stack(
                children: <Widget>[
                  SlideTransition(
                    position: new Tween<Offset>(
                      begin: const Offset(0.0, 0.0),
                      end: const Offset(-1.0, 0.0),
                    ).animate(animation),
                    child: exitPage,
                  ),
                  SlideTransition(
                    position: new Tween<Offset>(
                      begin: const Offset(1.0, 0.0),
                      end: Offset.zero,
                    ).animate(animation),
                    child: enterPage,
                  )
                ],
              ),
        );
}
```
**Usage**
```
Navigator.push(context,
    EnterExitRoute(exitPage: this, enterPage: Screen2()))
```
Seems to work well, so I'll make a PR for it if you like

**Comment by kalismeras61** [comment]
@benwinding what is different beetwen rightToLeftSlide and you work ? Have you tried rightToLeft slide with this package ?

**Comment by benwinding** [comment]
Hi @kalismeras61,
Thanks for the fast response, but the `rightToLeft` type isn't the same, on your implementation the new page overlaps the current page. 

What I'm looking for is for the new page to _push_ the old page out, as if they're joined together (not overlap). Does that make sense?
Cheers,
Ben
