### ISSUE TITLE
Remove pkg:test as a direct dependency

### ISSUE THREAD

**Issue by kevmoo** [kalismeras61/flutter_page_transition#39]
https://github.com/kalismeras61/flutter_page_transition/blob/fcde655270103706c6df2b51709ad0781e6aa14c/pubspec.yaml#L12

Pretty certain this is NOT needed at runtime.

**Comment by kalismeras61** [comment]
@kevmoo  you are right, I've tried a few things. I added it by mistake. Removed!

**Comment by kevmoo** [comment]
No worries. Just noticed it. Thanks for doing the safe transition!
