### ISSUE TITLE
Hero transition not working after moving to flutter 1.22.5

### ISSUE THREAD

**Issue by PavieOlivier** [kalismeras61/flutter_page_transition#40]
Is it normal ? after upgrading my flutter SDK to 1.22.5, Hero animations stopped working with your package

**Comment by oguz42** [comment]
same issue here

**Comment by kalismeras61** [comment]
@PavieOlivier  and @oguz42  Can you test with 1.1.7+6  ?

**Comment by PavieOlivier** [comment]
Just tried, and it's not fixing anything ?

**Comment by kalismeras61** [comment]
@PavieOlivier , i tested with latest stable, no issue. You have provide some code. Are you using Navigator widget somewhere ?

**Comment by PavieOlivier** [comment]
this is how i navigate from one page to another page

`Navigator.pushAndRemoveUntil(
              context,
              PageTransition(
                  duration: Duration(milliseconds: 500),
                  child: HomeScreen(),
                  type: PageTransitionType.fade),
              (route) => false);`

I am on Flutter 1.22.5 • channel stable 
is there something that I am missing ?

**Comment by PavieOlivier** [comment]
> same issue here

@oguz42  any update from your side ? i am trying, nothing works

**Comment by aryan29** [comment]
Same issue it is not working on flutter 1.22.5

**Comment by Curvel** [comment]
Works again with:

```
Flutter 1.26.0-13.0.pre.119 • channel master • https://github.com/flutter/flutter.git
Framework • revision 32db0fe791 (3 hours ago) • 2021-01-21 23:04:03 -0800
Engine • revision 90641fa923
Tools • Dart 2.12.0 (build 2.12.0-248.0.dev)
```
