### ISSUE TITLE
the page navigate to using the transition from the package will disable swipe left to return gesture on iOS

### ISSUE THREAD

**Issue by renntbenrennt** [kalismeras61/flutter_page_transition#44]
As stated on the title, this issue is tested even from the example project.

I wonder if this is intended or is there a way to workaround this...?

Thank you.

And we really need the default return gesture provided from iOS... so... yeah, thanks again!

**Comment by ProtoManGG** [comment]
Indeed please look into this !

**Comment by AgustinV08** [comment]
Same issue here, thanks for reporting

**Comment by djsjr** [comment]
Exactly what I came here to bring up. Please implement a solution!

**Comment by kalismeras61** [comment]
This is flutter issue all transitions in PageRouteBuilder so it wont work gesture swipe on IOS. 

Here is the issue still open status. 
https://github.com/flutter/flutter/issues/47441

**Comment by carlleeswanson** [comment]
Why "wontfix"? 
The flutter issue https://github.com/flutter/flutter/issues/47441 explains how to handle this.
It seems like the workaround described there could be applied to the flutter_page_transition package
