### ISSUE TITLE
Waiting for update 

### ISSUE THREAD

**Issue by zakblacki** [kalismeras61/flutter_page_transition#46]
> Because app depends on animated_splash_screen 1.1.0 which depends on page_transition 2.0.1-nullsafety.0, page_transition 2.0.1-nullsafety.0 is required.
> So, because app depends on page_transition ^1.1.7, version solving failed.
> pub get failed (1; So, because app depends on page_transition ^1.1.7, version solving failed.)

**Comment by kalismeras61** [comment]
Didn't understand ? you cab upgrade package. it is already there.

**Comment by kalismeras61** [comment]
page_transition: 2.0.1-nullsafety.0

**Comment by kalismeras61** [comment]
Published directly null-safety version
https://pub.dev/packages/page_transition
