### ISSUE TITLE
leftToRightJoined: getting childCurrent from generateRoute(...)

### ISSUE THREAD

**Issue by jimmyff** [kalismeras61/flutter_page_transition#50]
Hi, is there a way to get hold of the current page widget (for `childCurrent`) from `generateRoute(RouteSettings)` ?

If so it would be great to maybe add that to the example in the readme for the package?

**Comment by VinhNgT** [comment]
I'm having the same question, currently there is no clear way to find childCurrent when using predefined routes. So the transitions that require it won't work with go_router or AutoRoute

**Comment by VinhNgT** [comment]
Upon further research, I have found that SharedAxisTransition of https://pub.dev/packages/animations can animate both the before and after page/screen without the need to use 'childCurrent'. Maybe we should look at how it is implemented

**Comment by kalismeras61** [comment]
This has been fixed added new transitions methods
