### ISSUE TITLE
it's normal getting delay first time?

### ISSUE THREAD

**Issue by jordanjanaq** [kalismeras61/flutter_page_transition#52]
I'm using animation bottomToTop and first time has delay even not show completly animation.

<img width="436" alt="Captura de Pantalla 2021-09-08 a la(s) 12 56 59" src="https://user-images.githubusercontent.com/48919342/132560311-29afdaa5-c0d7-49ff-bb35-7b41b3b03074.png">

**Comment by kalismeras61** [comment]
There was some issue with the flutter itself please use 2.5.1 if you are using 2.5.0 and also default duration is 300 ms.
