### ISSUE TITLE
animated_splash_screen 1.1.0 depends on page_transition 2.0.1-nullsafety

### ISSUE THREAD

**Issue by zakblacki** [kalismeras61/flutter_page_transition#55]
Fix this please 

> Because animated_splash_screen 1.1.0 depends on page_transition 2.0.1-nullsafety.0 and no versions of animated_splash_screen match >1.1.0 <2.0.0, animated_splash_screen ^1.1.0 requires page_transition 2.0.1-nullsafety.0.
So, because fayda depends on both animated_splash_screen ^1.1.0 and page_transition ^2.0.4, version solving failed.
pub get failed (1; So, because fayda depends on both animated_splash_screen ^1.1.0 and page_transition ^2.0.4, version solving failed.)

**Comment by kalismeras61** [comment]
You have create issue for animated_splash_screen package. It is using old version of this package or you can override dependencies
