### ISSUE TITLE
Ability to apply transitions on previous route.

### ISSUE THREAD

**Issue by m-zaink** [kalismeras61/flutter_page_transition#58]
Why haven't you added the ability to transition the previous route and the current route yet? 

Something like the `ExitRoute` in [this article](https://medium.com/flutter-community/everything-you-need-to-know-about-flutter-page-route-transition-9ef5c1b32823).

**Comment by kalismeras61** [comment]
This package already has same functionality. You can use leftToRightJoined, rightToLeftJoined and also bottom and top joined transitions.
