### ISSUE TITLE
Top To Bottom Joined?

### ISSUE THREAD

**Issue by jtkeyva** [kalismeras61/flutter_page_transition#60]
Is it possible to have topToBottomJoined and bottomToTopJoined the same way it works for left/right joined?

**Comment by kalismeras61** [comment]
Yeah this can be done. Will  be next build.

**Comment by jtkeyva** [comment]
Awesome! thanks @kalismeras61

**Comment by kalismeras61** [comment]
This is has been done. Please use page_transition: ^2.0.5

**Comment by jtkeyva** [comment]
awesome thanks!!
