### ISSUE TITLE
PageTransition + PushNamed

### ISSUE THREAD

**Issue by softplace-io** [kalismeras61/flutter_page_transition#61]
Hello, 
I would like to know how I make a transition with Named + Animation?

**With Push:** 
Navigator.push(context, PageTransition(type: PageTransitionType.rightToLeft, child: DetailScreen()));

**With Named:** 
Navigator.pushNamed(context, PageTransition(type: PageTransitionType.rightToLeft, child: DetailScreen())) ???

Thanks a lot!

**Comment by kalismeras61** [comment]
Hi, have you read Readme file ? There is a section for explaining named routes.

**Comment by softplace-io** [comment]
Could you please tell me the url?

**Comment by kalismeras61** [comment]
have a look

https://github.com/kalismeras61/flutter_page_transition#usage-for-predefined-routes

**Comment by kalismeras61** [comment]
I am closing this. I hope above helps.
