### ISSUE TITLE
Diagonal / Multi-Page Transition

### ISSUE THREAD

**Issue by jtkeyva** [kalismeras61/flutter_page_transition#62]
Wondering if it's possible to have the whole app feel like a single canvas with pages on a grid? And you can transition from one grid to another no matter where it is and it will transition passing through other pages? Could be a bit tricky...

For instance, if you go from PAGE 1 to PAGE 9 it transitions diagonally through PAGE 5?

--------------------------
PAGE 1 | PAGE 2 | PAGE 3
--------------------------
PAGE 4 | PAGE 5 | PAGE 6
--------------------------
PAGE 7 | PAGE 8 | PAGE 9
--------------------------

Thanks

**Comment by kalismeras61** [comment]
Should be ok with flutter 3.27 !
