### ISSUE TITLE
Use with go_router, auto_route, beamer etc

### ISSUE THREAD

**Issue by jtkeyva** [kalismeras61/flutter_page_transition#63]
This is great! Awesome to see joined top/bottom and bottom/top working great now! Wondering if this is compatible with other routing libraries like go_router, auto_route, beamer etc? Some offer custom transitions, but not as artistically robust out of the box.
Thanks

**Comment by FreddyStraub** [comment]
I would also love to use those transitions with go_router 😍

**Comment by darkwilly08** [comment]
Hi guys! I do not it is the best approach but I make it works with go_router doing the following =>

```dart
    GoRoute(
      path: '/home',
      pageBuilder: (context, state) => CustomTransitionPage(
        child: const MyHomePage(),
        transitionsBuilder: ((context, animation, secondaryAnimation, child) {
          return PageTransition(
            child: child,
            type: PageTransitionType.scale,
          ).buildTransitions(
            context,
            animation,
            secondaryAnimation,
            child,
          );
        }),
      ),
    ),
```

I hope that help you!

**Comment by agelospanagiotakis** [comment]
> Hi guys! I do not know if it is the best approach but I make it works with go_router doing the following =>
> 
> ```dart
>     GoRoute(
>       path: '/home',
>       pageBuilder: (context, state) => CustomTransitionPage(
>         child: const MyHomePage(),
>         transitionsBuilder: ((context, animation, secondaryAnimation, child) {
>           return PageTransition(
>             child: child,
>             type: PageTransitionType.scale,
>             alignment: Alignment.center,
>           ).buildTransitions(
>             context,
>             animation,
>             secondaryAnimation,
>             child,
>           );
>         }),
>       ),
>     ),
> ```
> 
> I hope that help you!

i will try this approach today!
