### ISSUE TITLE
iOS swipe-to-go-back

### ISSUE THREAD

**Issue by carlleeswanson** [kalismeras61/flutter_page_transition#69]
Issue #64 and Issue #44 have been closed as "wontfix", with the stated reason being that the problem is within flutter (https://github.com/flutter/flutter/issues/47441).

However, the flutter issue actually does describe two different workarounds. It seems that one of these could be applied to this package to give it the requested functionality. Any chance of that happening?

**Comment by carlleeswanson** [comment]
Thank you for adding that @kalismeras61 !!

I tested with v2.0.8 and swipe-back works as described with the rightToLeft and fade animations. :)

But there appears to be a slight additional problem with this new feature... When isIos=true, the fade animation doesn't do a fade. Instead it does a rightToLeft.

**Comment by carlleeswanson** [comment]
Is it possible to make this also work with PageTransitionType.scale?

**Comment by carlleeswanson** [comment]
@kalismeras61 I tested PageTransitionType.scale in 2.0.9 with isIos=true. It works, but not in the way I would expect. It has the same issue as fade.

When isIos=false, fade and scale transitions occur directly into the currently displayed pane.
When isIos=true, fade and scale transitions cause a visible right-to-left transition of a new pane (same as you get when configured for right-to-left). The fade/scale occur into this new pane.

So while the fade and scale transitions work (i.e. they function and don't break anything), they behave oddly. I would expect them to occur "in place" without seeing the underlying right-to-left transition.

If possible, I would prefer to not see the right-to-left transition that occurs "underneath". If that's not possible, the new isIos feature is still useful, but the transitions are much less visually appealing than when isIos=false.

**Comment by rajeshbdabhi** [comment]
I have used isIos=true with rightToLeft animation and it is working fine but not working when I add WillPopScope it not calling onWillPop method.

**Comment by JeffyLo94** [comment]
> I have used isIos=true with rightToLeft animation and it is working fine but not working when I add WillPopScope it not calling onWillPop method.

I think this an actively debated flutter issue: Read more here https://github.com/flutter/flutter/issues/14203

**Comment by M-Yahia2011** [comment]
is there any possibility to have the iOS swipe back with leftToRight?
