### ISSUE TITLE
How does the example work?

### ISSUE THREAD

**Issue by justinjk007** [kalismeras61/flutter_page_transition#7]
I'm not seeing you importing any of your package files in `main.dart` , I get these error when I use one of the style
```
Compiler message:
lib/new_records.dart:161:27: Error: Getter not found: 'PageTransitionType'.
                    type: PageTransitionType.scale,
                          ^^^^^^^^^^^^^^^^^^
lib/new_records.dart:160:17: Error: Method not found: 'PageTransition'.
                PageTransition(
                ^^^^^^^^^^^^^^
```

**Comment by justinjk007** [comment]
Maybe you should add this  `import 'package:page_transition/page_transition.dart';` which worked for me. Great package btw.

**Comment by kalismeras61** [comment]
Thanks for the issue but if you look at the package installation tab you will find how to import packages.
