### ISSUE TITLE
Initializing global PageTransition

### ISSUE THREAD

**Issue by Samleet** [kalismeras61/flutter_page_transition#75]
Is it posiible to declare the page transition once and wrap all routes on it rather than having to implement the TransitionType on every route builder?

**Comment by kalismeras61** [comment]
This should work please use like it. 

 theme: ThemeData(
        primarySwatch: Colors.blue,
        pageTransitionsTheme: PageTransitionsTheme(
          builders: {
            TargetPlatform.iOS:
                PageTransition(type: PageTransitionType.fade, child: this)
                    .matchingBuilder,
          },
        ),
      ),
