### ISSUE TITLE
Joined transition improvement - animating old screen instead of its mockup.

### ISSUE THREAD

**Issue by kmrosiek** [kalismeras61/flutter_page_transition#79]
Current implementation of joined transition covers old page with Widget pretending it is animating the old page whereas it animated widget that covers old page. 

The problem appears when you try to make joined animation from page that is scrollable and scroll has position != 0. You can see the screen substitution first and then the animation. I guess the same might apply to statefulwidget. 

[Sample](https://user-images.githubusercontent.com/26028381/208665056-da1b2ffd-c58d-49da-acdd-1b227e0420b7.mp4)

Do you think there is any way this animation can be improved?

**Comment by kalismeras61** [comment]
This is probably IOS junk issue. If you switch new flutter rendering engine impeller, I think the performance will be better.

**Comment by kalien1** [comment]
I have the same problem on android. were you able to solve it?

**Comment by kalismeras61** [comment]
This issues has been fixed by impeller engine please use it.
