### ISSUE TITLE
Change the duration time of the transition ?

### ISSUE THREAD

**Issue by pascalf22** [kalismeras61/flutter_page_transition#8]
Heelo @kalismeras61 !

Thanks for the flutter_page_transition. I love it !

Is it possible to change the duration time of the transition?

Thanks a lot !

Pascal

**Comment by kalismeras61** [comment]
Yes you can change duration. Default duration time is Duration(milliseconds: 300),


PageTransition(type: PageTransitionType.fade, duration: Duration(milliseconds: 500),child: SecondPage()))

**Comment by pascalf22** [comment]
Hello @kalismeras61 !

Perfect !!! Thanks a lot ! It work ! 

Have a great day ! 

Pascal
