### ISSUE TITLE
onGenerateRoute 

### ISSUE THREAD

**Issue by only2433** [kalismeras61/flutter_page_transition#86]
Using onGenerateRoute, I want to implement PageTransitionType.rightToLeftJoined.

**Comment by kalismeras61** [comment]
> Using onGenerateRoute, I want to implement PageTransitionType.rightToLeftJoined.

 onGenerateRoute: (settings) {
    switch (settings.name) {
      case '/second':
        return PageTransition(child: SecondPage(), type: PageTransitionType.rightToLeftJoined);
        break;
      default:
        return null;
    }
  },

**Comment by s4nk37** [comment]
Not working getting error saying in onGenerateRoute switch statement.
`The return type 'Object' isn't a 'Widget', as required by the closure's context. `

**Comment by kalismeras61** [comment]
Has been fixed with latest flutter 2.37 also 2.2.0 page transition!
