### ISSUE TITLE
Performance degradation: Frame rate drops to 60 FPS after using page_transition

### ISSUE THREAD

**Issue by nobu121** [kalismeras61/flutter_page_transition#89]
Hello,

I've encountered a performance issue when using the page_transition package in my Flutter application. I wanted to bring this to your attention and provide some details about the problem.

Issue Description:
- Before using page_transition, my app runs smoothly at 120 FPS.
- After implementing page_transition for navigating to another page, the frame rate drops to 60 FPS.
- The reduced frame rate persists even after returning to other pages in the app.

Steps to Reproduce:
1. Start with a Flutter app running at 120 FPS.
2. Implement page_transition for navigation, e.g.:
   ```dart
   Navigator.push(
     context,
     PageTransition(
       type: PageTransitionType.bottomToTop,
       child: OtherPage,
     ),
   );
   ```
3. Navigate to the page using the transition.
4. Observe the frame rate drop to 60 FPS.
5. Return to other pages in the app.
6. Notice that the frame rate remains at 60 FPS and doesn't recover to 120 FPS.

Environment:
- Flutter version: 3.24.2
- page_transition version: 2.1.0
- OS: Android 14

I hope this information helps in identifying and addressing the issue. Please let me know if you need any additional details or if there's anything I can do to assist in resolving this problem.

Thank you for your time and effort in maintaining this package.

**Comment by kalismeras61** [comment]
I added some tips for performance please have a look

`For optimal performance:

Keep transition durations short (200-300ms)
Use simpler curves like Curves.easeOut
Avoid complex transitions for frequent navigation
Consider using childBuilder for lazy widget construction
Use RepaintBoundary on heavy widgets being transitioned
context.pushTransition(
  type: PageTransitionType.fade, // Simpler transitions are more performant
  duration: Duration(milliseconds: 200),
  curve: Curves.easeOut,
  child: RepaintBoundary(
    child: HeavyWidget(),
  ),
);`
